# Generated by Django 5.0.4 on 2024-04-09 13:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creatures',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('image', models.CharField(blank=True)),
                ('description', models.TextField()),
                ('location', models.CharField()),
                ('drops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None)),
            ],
        ),
    ]
