# Generated by Django 5.0.4 on 2024-04-09 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenDexApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatures',
            name='drops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='creatures',
            name='image',
            field=models.CharField(blank=True, default=''),
        ),
    ]
