# Generated by Django 5.0.4 on 2024-04-17 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe tener el formatgo: '+999999999'. Hasta 15 dígitos es válido.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
