# Generated by Django 5.0.4 on 2024-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implicados', models.TextField(blank=True)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=124)),
                ('testigos', models.TextField(blank=True)),
                ('avisado', models.BooleanField(blank=True)),
                ('pruebas', models.FileField(blank=True, null=True, upload_to='prueba/%Y/%m/%D/')),
            ],
        ),
    ]
