# Generated by Django 5.0.4 on 2024-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0002_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='contraseña',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='token',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
