# Generated by Django 5.0.4 on 2024-04-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0004_consulta_delete_comunicado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Comunicado',
        ),
    ]
