# Generated by Django 5.0.4 on 2024-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0005_rename_consulta_comunicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comunicado',
        ),
    ]
