# Generated by Django 5.0.4 on 2024-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0008_comunicado_solucionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('1', 'Incumplimiento de la legislación y/o normas internas'), ('2', 'Actuación inadecuada, no ética, o falta de integridad en el desempeño profesional'), ('3', 'Trato irrespetuoso, desigual o injusto'), ('4', 'Discriminación o violación de los derechos humanos'), ('5', 'Violencia, acoso o abuso'), ('6', 'Corrupción y/o fraude'), ('7', 'Conducta relacionada con el blanqueo de capitales'), ('8', 'Daños contra el medio ambiente'), ('9', 'Riegos de seguridad y salud'), ('10', 'Actos contra la libre competencia'), ('11', 'Infracción de la normativa de protección de datos')], default='1', max_length=2),
        ),
    ]
