# Generated by Django 5.0.4 on 2024-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0010_alter_comunicado_avisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='avisado',
            field=models.BooleanField(choices=[('True', 'Si'), ('False', 'No'), ('', 'No lo sé')], default='False', null=True, verbose_name='Algún superior fue avisado?'),
        ),
    ]
