# Generated by Django 5.0.4 on 2024-04-18 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0011_alter_comunicado_avisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='comunicante',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='CanalEticoApp.usuario'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='contraseña',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('1', 'Incumplimiento de la legislación y/o normas internas'), ('2', 'Actuación inadecuada, no ética, o falta de integridad en el desempeño profesional'), ('3', 'Trato irrespetuoso, desigual o injusto'), ('4', 'Discriminación o violación de los derechos humanos'), ('5', 'Violencia, acoso o abuso'), ('6', 'Corrupción y/o fraude'), ('7', 'Conducta relacionada con el blanqueo de capitales'), ('8', 'Daños contra el medio ambiente'), ('9', 'Riesgos de seguridad y salud'), ('10', 'Actos contra la libre competencia'), ('11', 'Infracción de la normativa de protección de datos')], default='1', max_length=2),
        ),
    ]
