# Generated by Django 5.0.4 on 2024-04-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0012_comunicado_comunicante_alter_comunicado_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='avisado',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default='', null=True, verbose_name='Algún superior fue avisado?'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='comunicante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CanalEticoApp.usuario'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='token',
            field=models.CharField(max_length=12, unique=True, verbose_name='Código del comunicado'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='CanalEticoApp.tipo'),
        ),
    ]
