# Generated by Django 5.0.4 on 2024-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0013_tipo_alter_comunicado_avisado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(blank=True, max_length=124),
        ),
    ]
