# Generated by Django 5.0.4 on 2024-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0014_alter_tipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
