# Generated by Django 5.0.4 on 2024-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanalEticoApp', '0015_alter_comunicado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='solucion',
            field=models.TextField(default='', null=True),
        ),
    ]
