# Generated by Django 5.0.4 on 2024-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatosAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Datos',
        ),
    ]
